name: camera_platform_interface_frame
description: A common platform interface for the camera plugin.
repository: https://github.com/zhukeev/camera_platform_interface_frame
issue_tracker: https://github.com/zhukeev/camera_platform_interface_frame/issues
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.10.12

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  cross_file: ^0.3.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  stream_transform: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  leak_tracker_flutter_testing: any

topics:
  - camera
